version: '3'
services:
  # php:
  #   image: php:7.3.1

  mysql:
    image: mysql:5.7.25
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DATA_PATH}:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin:4.7
    environment:
      PMA_HOST: mysql
    ports:
      - 10000:80

  apache:
    build:
      context: ./apache
      dockerfile: Dockerfile
    volumes:
      - ${WWW_PATH}/*:/var/www/html
    ports:
      - 9000:80
